// lib/ml/seed-outcomes.ts
// Synthetic historical employee outcome dataset for calibration demo
import type { EmployeeOutcome } from "@/lib/types"

const c = (n: number, lo = 0, hi = 1) => Math.max(lo, Math.min(hi, n))

export const SEED_OUTCOMES: EmployeeOutcome[] = [
  // Engineering
  {
    employeeId: "emp_eng_001",
    hiredAt: "2024-02-12",
    department: "Engineering",
    role: "Frontend Engineer",
    level: "Mid",
    team: "Growth",
    featureSnapshot: {
      cs_verified: 0.74,
      cs_total: 0.82,
      xs: 0.68,
      forgeScore: c(0.82 * 0.68),
      proofConfidence: 0.78,
      forkRatio: 0.12,
      burstiness: 0.18,
      recency: 0.86,
      teamwork: 0.66,
      communication: 0.72,
      adaptability: 0.61,
      ownership: 0.7,
      missingSkillsCount: 1,
      weakSkillsCount: 1,
      nonGithubSignalsPresent: 0,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 4,
      rampTimeDays: 38,
      regrettedHire: false,
      notes: "Shipped onboarding revamp; consistent PR hygiene.",
    },
  },
  {
    employeeId: "emp_eng_002",
    hiredAt: "2024-03-01",
    department: "Engineering",
    role: "Backend Engineer",
    level: "Senior",
    team: "Platform",
    featureSnapshot: {
      cs_verified: 0.81,
      cs_total: 0.86,
      xs: 0.74,
      forgeScore: c(0.86 * 0.74),
      proofConfidence: 0.84,
      forkRatio: 0.08,
      burstiness: 0.12,
      recency: 0.78,
      teamwork: 0.71,
      communication: 0.64,
      adaptability: 0.7,
      ownership: 0.83,
      missingSkillsCount: 0,
      weakSkillsCount: 1,
      nonGithubSignalsPresent: 0,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 5,
      rampTimeDays: 28,
      regrettedHire: false,
      notes: "Owned incident response + improved observability.",
    },
  },
  {
    employeeId: "emp_eng_003",
    hiredAt: "2024-04-15",
    department: "Engineering",
    role: "Full Stack Engineer",
    level: "Junior",
    team: "Core App",
    featureSnapshot: {
      cs_verified: 0.58,
      cs_total: 0.69,
      xs: 0.66,
      forgeScore: c(0.69 * 0.66),
      proofConfidence: 0.62,
      forkRatio: 0.2,
      burstiness: 0.22,
      recency: 0.92,
      teamwork: 0.62,
      communication: 0.58,
      adaptability: 0.74,
      ownership: 0.55,
      missingSkillsCount: 2,
      weakSkillsCount: 2,
      nonGithubSignalsPresent: 0,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 4,
      rampTimeDays: 52,
      regrettedHire: false,
      notes: "High learning velocity; needed guidance early.",
    },
  },
  {
    employeeId: "emp_eng_004",
    hiredAt: "2024-05-03",
    department: "Engineering",
    role: "Data Engineer",
    level: "Mid",
    team: "Analytics",
    featureSnapshot: {
      cs_verified: 0.69,
      cs_total: 0.76,
      xs: 0.63,
      forgeScore: c(0.76 * 0.63),
      proofConfidence: 0.73,
      forkRatio: 0.1,
      burstiness: 0.25,
      recency: 0.72,
      teamwork: 0.6,
      communication: 0.55,
      adaptability: 0.66,
      ownership: 0.64,
      missingSkillsCount: 1,
      weakSkillsCount: 2,
      nonGithubSignalsPresent: 0,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 4,
      rampTimeDays: 45,
      regrettedHire: false,
      notes: "Delivered ETL reliability fixes; docs initially light.",
    },
  },
  {
    employeeId: "emp_eng_005",
    hiredAt: "2024-01-20",
    department: "Engineering",
    role: "Frontend Engineer",
    level: "Mid",
    team: "Design Systems",
    featureSnapshot: {
      cs_verified: 0.62,
      cs_total: 0.77,
      xs: 0.49,
      forgeScore: c(0.77 * 0.49),
      proofConfidence: 0.58,
      forkRatio: 0.34,
      burstiness: 0.55,
      recency: 0.64,
      teamwork: 0.4,
      communication: 0.46,
      adaptability: 0.54,
      ownership: 0.45,
      missingSkillsCount: 1,
      weakSkillsCount: 2,
      nonGithubSignalsPresent: 0,
    },
    outcome: {
      probationPassed: false,
      managerRating1to5: 2,
      rampTimeDays: 75,
      regrettedHire: true,
      notes: "Output inconsistent; collaboration friction.",
    },
  },

  // Product
  {
    employeeId: "emp_pm_001",
    hiredAt: "2024-02-28",
    department: "Product",
    role: "Product Manager",
    level: "Senior",
    team: "Monetization",
    featureSnapshot: {
      cs_verified: 0.63,
      cs_total: 0.71,
      xs: 0.78,
      forgeScore: c(0.71 * 0.78),
      proofConfidence: 0.66,
      forkRatio: 0.0,
      burstiness: 0.12,
      recency: 0.81,
      teamwork: 0.82,
      communication: 0.86,
      adaptability: 0.7,
      ownership: 0.77,
      missingSkillsCount: 1,
      weakSkillsCount: 1,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 5,
      rampTimeDays: 32,
      regrettedHire: false,
      notes: "Clear PRDs + crisp tradeoffs; strong xfn alignment.",
    },
  },
  {
    employeeId: "emp_pm_002",
    hiredAt: "2024-06-10",
    department: "Product",
    role: "Associate PM",
    level: "Junior",
    team: "Core App",
    featureSnapshot: {
      cs_verified: 0.48,
      cs_total: 0.62,
      xs: 0.73,
      forgeScore: c(0.62 * 0.73),
      proofConfidence: 0.52,
      forkRatio: 0.0,
      burstiness: 0.2,
      recency: 0.88,
      teamwork: 0.76,
      communication: 0.7,
      adaptability: 0.78,
      ownership: 0.62,
      missingSkillsCount: 2,
      weakSkillsCount: 2,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 4,
      rampTimeDays: 58,
      regrettedHire: false,
      notes: "Solid growth; needed coaching on prioritization.",
    },
  },
  {
    employeeId: "emp_pm_003",
    hiredAt: "2024-04-02",
    department: "Product",
    role: "Product Manager",
    level: "Mid",
    team: "Search",
    featureSnapshot: {
      cs_verified: 0.52,
      cs_total: 0.68,
      xs: 0.6,
      forgeScore: c(0.68 * 0.6),
      proofConfidence: 0.5,
      forkRatio: 0.0,
      burstiness: 0.35,
      recency: 0.6,
      teamwork: 0.58,
      communication: 0.61,
      adaptability: 0.55,
      ownership: 0.57,
      missingSkillsCount: 2,
      weakSkillsCount: 3,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: false,
      managerRating1to5: 3,
      rampTimeDays: 80,
      regrettedHire: true,
      notes: "Execution okay; weak alignment + unclear success metrics.",
    },
  },

  // Design
  {
    employeeId: "emp_des_001",
    hiredAt: "2024-03-18",
    department: "Design",
    role: "Product Designer",
    level: "Senior",
    team: "Core UX",
    featureSnapshot: {
      cs_verified: 0.61,
      cs_total: 0.7,
      xs: 0.8,
      forgeScore: c(0.7 * 0.8),
      proofConfidence: 0.69,
      forkRatio: 0.0,
      burstiness: 0.1,
      recency: 0.84,
      teamwork: 0.85,
      communication: 0.82,
      adaptability: 0.71,
      ownership: 0.76,
      missingSkillsCount: 1,
      weakSkillsCount: 1,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 5,
      rampTimeDays: 29,
      regrettedHire: false,
      notes: "Case studies strong; tight handoff docs.",
    },
  },
  {
    employeeId: "emp_des_002",
    hiredAt: "2024-05-21",
    department: "Design",
    role: "UI Designer",
    level: "Mid",
    team: "Brand",
    featureSnapshot: {
      cs_verified: 0.44,
      cs_total: 0.62,
      xs: 0.71,
      forgeScore: c(0.62 * 0.71),
      proofConfidence: 0.46,
      forkRatio: 0.0,
      burstiness: 0.28,
      recency: 0.77,
      teamwork: 0.7,
      communication: 0.64,
      adaptability: 0.66,
      ownership: 0.6,
      missingSkillsCount: 2,
      weakSkillsCount: 2,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 4,
      rampTimeDays: 54,
      regrettedHire: false,
      notes: "Good visual craft; needed systems thinking coaching.",
    },
  },
  {
    employeeId: "emp_des_003",
    hiredAt: "2024-01-08",
    department: "Design",
    role: "Product Designer",
    level: "Mid",
    team: "Growth",
    featureSnapshot: {
      cs_verified: 0.39,
      cs_total: 0.6,
      xs: 0.58,
      forgeScore: c(0.6 * 0.58),
      proofConfidence: 0.41,
      forkRatio: 0.0,
      burstiness: 0.42,
      recency: 0.55,
      teamwork: 0.52,
      communication: 0.57,
      adaptability: 0.5,
      ownership: 0.48,
      missingSkillsCount: 3,
      weakSkillsCount: 3,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: false,
      managerRating1to5: 2,
      rampTimeDays: 88,
      regrettedHire: true,
      notes: "Portfolio thin; struggled with iteration speed.",
    },
  },

  // Recruiting
  {
    employeeId: "emp_rec_001",
    hiredAt: "2024-02-05",
    department: "Recruiting",
    role: "Technical Recruiter",
    level: "Senior",
    team: "Engineering Hiring",
    featureSnapshot: {
      cs_verified: 0.57,
      cs_total: 0.66,
      xs: 0.82,
      forgeScore: c(0.66 * 0.82),
      proofConfidence: 0.6,
      forkRatio: 0.0,
      burstiness: 0.12,
      recency: 0.8,
      teamwork: 0.86,
      communication: 0.88,
      adaptability: 0.68,
      ownership: 0.74,
      missingSkillsCount: 1,
      weakSkillsCount: 1,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 5,
      rampTimeDays: 30,
      regrettedHire: false,
      notes: "Improved funnel; excellent hiring manager feedback.",
    },
  },
  {
    employeeId: "emp_rec_002",
    hiredAt: "2024-06-02",
    department: "Recruiting",
    role: "Recruiting Coordinator",
    level: "Junior",
    team: "Ops",
    featureSnapshot: {
      cs_verified: 0.46,
      cs_total: 0.56,
      xs: 0.72,
      forgeScore: c(0.56 * 0.72),
      proofConfidence: 0.48,
      forkRatio: 0.0,
      burstiness: 0.18,
      recency: 0.83,
      teamwork: 0.74,
      communication: 0.7,
      adaptability: 0.66,
      ownership: 0.58,
      missingSkillsCount: 2,
      weakSkillsCount: 2,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 4,
      rampTimeDays: 60,
      regrettedHire: false,
      notes: "Solid scheduling + candidate comms; slower at first.",
    },
  },

  // Data
  {
    employeeId: "emp_data_001",
    hiredAt: "2024-03-25",
    department: "Data",
    role: "Data Analyst",
    level: "Mid",
    team: "Revenue",
    featureSnapshot: {
      cs_verified: 0.61,
      cs_total: 0.7,
      xs: 0.67,
      forgeScore: c(0.7 * 0.67),
      proofConfidence: 0.65,
      forkRatio: 0.0,
      burstiness: 0.16,
      recency: 0.79,
      teamwork: 0.64,
      communication: 0.72,
      adaptability: 0.6,
      ownership: 0.62,
      missingSkillsCount: 1,
      weakSkillsCount: 2,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 4,
      rampTimeDays: 44,
      regrettedHire: false,
      notes: "Clear dashboards; good stakeholder comms.",
    },
  },
  {
    employeeId: "emp_data_002",
    hiredAt: "2024-02-14",
    department: "Data",
    role: "Data Scientist",
    level: "Senior",
    team: "Recommendations",
    featureSnapshot: {
      cs_verified: 0.76,
      cs_total: 0.83,
      xs: 0.7,
      forgeScore: c(0.83 * 0.7),
      proofConfidence: 0.8,
      forkRatio: 0.0,
      burstiness: 0.14,
      recency: 0.74,
      teamwork: 0.68,
      communication: 0.61,
      adaptability: 0.72,
      ownership: 0.79,
      missingSkillsCount: 0,
      weakSkillsCount: 1,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 5,
      rampTimeDays: 34,
      regrettedHire: false,
      notes: "Strong modeling + pragmatic deployment mindset.",
    },
  },
  {
    employeeId: "emp_data_003",
    hiredAt: "2024-01-30",
    department: "Data",
    role: "Analytics Engineer",
    level: "Mid",
    team: "Warehouse",
    featureSnapshot: {
      cs_verified: 0.52,
      cs_total: 0.67,
      xs: 0.55,
      forgeScore: c(0.67 * 0.55),
      proofConfidence: 0.54,
      forkRatio: 0.0,
      burstiness: 0.3,
      recency: 0.6,
      teamwork: 0.54,
      communication: 0.5,
      adaptability: 0.58,
      ownership: 0.56,
      missingSkillsCount: 2,
      weakSkillsCount: 2,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: false,
      managerRating1to5: 3,
      rampTimeDays: 82,
      regrettedHire: true,
      notes: "Missed deadlines; weak ownership on pipelines.",
    },
  },

  // Operations
  {
    employeeId: "emp_ops_001",
    hiredAt: "2024-04-20",
    department: "Operations",
    role: "Operations Lead",
    level: "Lead",
    team: "BizOps",
    featureSnapshot: {
      cs_verified: 0.6,
      cs_total: 0.69,
      xs: 0.79,
      forgeScore: c(0.69 * 0.79),
      proofConfidence: 0.63,
      forkRatio: 0.0,
      burstiness: 0.1,
      recency: 0.76,
      teamwork: 0.84,
      communication: 0.78,
      adaptability: 0.71,
      ownership: 0.82,
      missingSkillsCount: 1,
      weakSkillsCount: 1,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 5,
      rampTimeDays: 36,
      regrettedHire: false,
      notes: "Clean processes; reduced cycle time; great cross-team trust.",
    },
  },
  {
    employeeId: "emp_ops_002",
    hiredAt: "2024-06-18",
    department: "Operations",
    role: "Operations Associate",
    level: "Junior",
    team: "Support Ops",
    featureSnapshot: {
      cs_verified: 0.43,
      cs_total: 0.58,
      xs: 0.7,
      forgeScore: c(0.58 * 0.7),
      proofConfidence: 0.45,
      forkRatio: 0.0,
      burstiness: 0.22,
      recency: 0.87,
      teamwork: 0.72,
      communication: 0.66,
      adaptability: 0.74,
      ownership: 0.56,
      missingSkillsCount: 2,
      weakSkillsCount: 2,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 4,
      rampTimeDays: 62,
      regrettedHire: false,
      notes: "Good trajectory; needed training on tooling.",
    },
  },

  // Marketing
  {
    employeeId: "emp_mkt_001",
    hiredAt: "2024-02-22",
    department: "Marketing",
    role: "Growth Marketer",
    level: "Senior",
    team: "Acquisition",
    featureSnapshot: {
      cs_verified: 0.55,
      cs_total: 0.64,
      xs: 0.76,
      forgeScore: c(0.64 * 0.76),
      proofConfidence: 0.58,
      forkRatio: 0.0,
      burstiness: 0.14,
      recency: 0.73,
      teamwork: 0.74,
      communication: 0.8,
      adaptability: 0.68,
      ownership: 0.7,
      missingSkillsCount: 1,
      weakSkillsCount: 1,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 5,
      rampTimeDays: 40,
      regrettedHire: false,
      notes: "Strong experimentation; clear post-mortems.",
    },
  },
  {
    employeeId: "emp_mkt_002",
    hiredAt: "2024-01-14",
    department: "Marketing",
    role: "Content Marketer",
    level: "Mid",
    team: "Brand",
    featureSnapshot: {
      cs_verified: 0.41,
      cs_total: 0.58,
      xs: 0.62,
      forgeScore: c(0.58 * 0.62),
      proofConfidence: 0.43,
      forkRatio: 0.0,
      burstiness: 0.33,
      recency: 0.58,
      teamwork: 0.6,
      communication: 0.66,
      adaptability: 0.55,
      ownership: 0.52,
      missingSkillsCount: 2,
      weakSkillsCount: 3,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: false,
      managerRating1to5: 3,
      rampTimeDays: 85,
      regrettedHire: true,
      notes: "Content output okay; weak ownership + inconsistent quality bar.",
    },
  },

  // Sales
  {
    employeeId: "emp_sales_001",
    hiredAt: "2024-03-08",
    department: "Sales",
    role: "Account Executive",
    level: "Mid",
    team: "Mid-Market",
    featureSnapshot: {
      cs_verified: 0.52,
      cs_total: 0.62,
      xs: 0.75,
      forgeScore: c(0.62 * 0.75),
      proofConfidence: 0.55,
      forkRatio: 0.0,
      burstiness: 0.16,
      recency: 0.71,
      teamwork: 0.72,
      communication: 0.82,
      adaptability: 0.62,
      ownership: 0.66,
      missingSkillsCount: 1,
      weakSkillsCount: 2,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 4,
      rampTimeDays: 57,
      regrettedHire: false,
      notes: "Hit ramp; good pipeline hygiene.",
    },
  },
  {
    employeeId: "emp_sales_002",
    hiredAt: "2024-04-11",
    department: "Sales",
    role: "SDR",
    level: "Junior",
    team: "Outbound",
    featureSnapshot: {
      cs_verified: 0.38,
      cs_total: 0.52,
      xs: 0.68,
      forgeScore: c(0.52 * 0.68),
      proofConfidence: 0.4,
      forkRatio: 0.0,
      burstiness: 0.28,
      recency: 0.9,
      teamwork: 0.62,
      communication: 0.7,
      adaptability: 0.76,
      ownership: 0.5,
      missingSkillsCount: 3,
      weakSkillsCount: 3,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 4,
      rampTimeDays: 70,
      regrettedHire: false,
      notes: "Slow start but strong improvement curve.",
    },
  },

  // Customer Success
  {
    employeeId: "emp_cs_001",
    hiredAt: "2024-02-02",
    department: "CustomerSuccess",
    role: "Customer Success Manager",
    level: "Senior",
    team: "Enterprise",
    featureSnapshot: {
      cs_verified: 0.56,
      cs_total: 0.65,
      xs: 0.8,
      forgeScore: c(0.65 * 0.8),
      proofConfidence: 0.6,
      forkRatio: 0.0,
      burstiness: 0.1,
      recency: 0.77,
      teamwork: 0.84,
      communication: 0.86,
      adaptability: 0.63,
      ownership: 0.72,
      missingSkillsCount: 1,
      weakSkillsCount: 1,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: true,
      managerRating1to5: 5,
      rampTimeDays: 41,
      regrettedHire: false,
      notes: "Excellent customer comms; renewals improved.",
    },
  },
  {
    employeeId: "emp_cs_002",
    hiredAt: "2024-01-19",
    department: "CustomerSuccess",
    role: "Support Specialist",
    level: "Junior",
    team: "SMB",
    featureSnapshot: {
      cs_verified: 0.34,
      cs_total: 0.5,
      xs: 0.64,
      forgeScore: c(0.5 * 0.64),
      proofConfidence: 0.38,
      forkRatio: 0.0,
      burstiness: 0.26,
      recency: 0.69,
      teamwork: 0.58,
      communication: 0.6,
      adaptability: 0.55,
      ownership: 0.44,
      missingSkillsCount: 3,
      weakSkillsCount: 3,
      nonGithubSignalsPresent: 1,
    },
    outcome: {
      probationPassed: false,
      managerRating1to5: 2,
      rampTimeDays: 92,
      regrettedHire: true,
      notes: "Couldn't maintain quality under load; weak ownership.",
    },
  },
]

// Derived summary for UI
export const SEED_OUTCOMES_META = (() => {
  const byDept: Record<string, number> = {}
  let sumRating = 0
  let success = 0
  for (const o of SEED_OUTCOMES) {
    byDept[o.department] = (byDept[o.department] ?? 0) + 1
    sumRating += o.outcome.managerRating1to5
    const label = o.outcome.probationPassed && o.outcome.managerRating1to5 >= 4 && !o.outcome.regrettedHire
    if (label) success += 1
  }
  return {
    n: SEED_OUTCOMES.length,
    byDept,
    avgRating: +(sumRating / SEED_OUTCOMES.length).toFixed(2),
    successRate: +((success / SEED_OUTCOMES.length) * 100).toFixed(1),
  }
})()
